clear all;
close all;
dim_x = 17; dim_y = 17;
axis([-1 dim_x -1 dim_y]);
rectangle('Position', [0, 0, 17, 17], 'linewidth',2);
for i=0:16
        rectangle('Position', [0, i, 17, 1]);
end

for i=0:16
        rectangle('Position', [i, 0, 1, 17]);
end

rectangle('Position',[1, 1, 1, 1], 'facecolor', 'black');
rectangle('Position',[2, 1, 1, 1], 'facecolor', 'black');
rectangle('Position',[3, 1, 1, 1], 'facecolor', 'black');
rectangle('Position',[7, 1, 1, 1], 'facecolor', 'black');
rectangle('Position',[8, 1, 1, 1], 'facecolor', 'black');
rectangle('Position',[9, 1, 1, 1], 'facecolor', 'black');
rectangle('Position',[13, 1, 1, 1], 'facecolor', 'black');
rectangle('Position',[14, 1, 1, 1], 'facecolor', 'black');
rectangle('Position',[15, 1, 1, 1], 'facecolor', 'black');
rectangle('Position',[1, 2, 1, 1], 'facecolor', 'black');
rectangle('Position',[2, 2, 1, 1], 'facecolor', 'black');
rectangle('Position',[3, 2, 1, 1], 'facecolor', 'black');
rectangle('Position',[7, 2, 1, 1], 'facecolor', 'black');
rectangle('Position',[8, 2, 1, 1], 'facecolor', 'black');
rectangle('Position',[9, 2, 1, 1], 'facecolor', 'black');
rectangle('Position',[13, 2, 1, 1], 'facecolor', 'black');
rectangle('Position',[14, 2, 1, 1], 'facecolor', 'black');
rectangle('Position',[15, 2, 1, 1], 'facecolor', 'black');
rectangle('Position',[1, 3, 1, 1], 'facecolor', 'black');
rectangle('Position',[2, 3, 1, 1], 'facecolor', 'black');
rectangle('Position',[3, 3, 1, 1], 'facecolor', 'black');
rectangle('Position',[7, 3, 1, 1], 'facecolor', 'black');
rectangle('Position',[8, 3, 1, 1], 'facecolor', 'black');
rectangle('Position',[9, 3, 1, 1], 'facecolor', 'black');
rectangle('Position',[13, 3, 1, 1], 'facecolor', 'black');
rectangle('Position',[14, 3, 1, 1], 'facecolor', 'black');
rectangle('Position',[15, 3, 1, 1], 'facecolor', 'black');
rectangle('Position',[1, 7, 1, 1], 'facecolor', 'black');
rectangle('Position',[2, 7, 1, 1], 'facecolor', 'black');
rectangle('Position',[3, 7, 1, 1], 'facecolor', 'black');
rectangle('Position',[7, 7, 1, 1], 'facecolor', 'black');
rectangle('Position',[8, 7, 1, 1], 'facecolor', 'black');
rectangle('Position',[9, 7, 1, 1], 'facecolor', 'black');
rectangle('Position',[13, 7, 1, 1], 'facecolor', 'black');
rectangle('Position',[14, 7, 1, 1], 'facecolor', 'black');
rectangle('Position',[15, 7, 1, 1], 'facecolor', 'black');
rectangle('Position',[1, 8, 1, 1], 'facecolor', 'black');
rectangle('Position',[2, 8, 1, 1], 'facecolor', 'black');
rectangle('Position',[3, 8, 1, 1], 'facecolor', 'black');
rectangle('Position',[7, 8, 1, 1], 'facecolor', 'black');
rectangle('Position',[8, 8, 1, 1], 'facecolor', 'black');
rectangle('Position',[9, 8, 1, 1], 'facecolor', 'black');
rectangle('Position',[13, 8, 1, 1], 'facecolor', 'black');
rectangle('Position',[14, 8, 1, 1], 'facecolor', 'black');
rectangle('Position',[15, 8, 1, 1], 'facecolor', 'black');
rectangle('Position',[1, 9, 1, 1], 'facecolor', 'black');
rectangle('Position',[2, 9, 1, 1], 'facecolor', 'black');
rectangle('Position',[3, 9, 1, 1], 'facecolor', 'black');
rectangle('Position',[7, 9, 1, 1], 'facecolor', 'black');
rectangle('Position',[8, 9, 1, 1], 'facecolor', 'black');
rectangle('Position',[9, 9, 1, 1], 'facecolor', 'black');
rectangle('Position',[13, 9, 1, 1], 'facecolor', 'black');
rectangle('Position',[14, 9, 1, 1], 'facecolor', 'black');
rectangle('Position',[15, 9, 1, 1], 'facecolor', 'black');
rectangle('Position',[1, 13, 1, 1], 'facecolor', 'black');
rectangle('Position',[2, 13, 1, 1], 'facecolor', 'black');
rectangle('Position',[3, 13, 1, 1], 'facecolor', 'black');
rectangle('Position',[7, 13, 1, 1], 'facecolor', 'black');
rectangle('Position',[8, 13, 1, 1], 'facecolor', 'black');
rectangle('Position',[9, 13, 1, 1], 'facecolor', 'black');
rectangle('Position',[13, 13, 1, 1], 'facecolor', 'black');
rectangle('Position',[14, 13, 1, 1], 'facecolor', 'black');
rectangle('Position',[15, 13, 1, 1], 'facecolor', 'black');
rectangle('Position',[1, 14, 1, 1], 'facecolor', 'black');
rectangle('Position',[2, 14, 1, 1], 'facecolor', 'black');
rectangle('Position',[3, 14, 1, 1], 'facecolor', 'black');
rectangle('Position',[7, 14, 1, 1], 'facecolor', 'black');
rectangle('Position',[8, 14, 1, 1], 'facecolor', 'black');
rectangle('Position',[9, 14, 1, 1], 'facecolor', 'black');
rectangle('Position',[13, 14, 1, 1], 'facecolor', 'black');
rectangle('Position',[14, 14, 1, 1], 'facecolor', 'black');
rectangle('Position',[15, 14, 1, 1], 'facecolor', 'black');
rectangle('Position',[1, 15, 1, 1], 'facecolor', 'black');
rectangle('Position',[2, 15, 1, 1], 'facecolor', 'black');
rectangle('Position',[3, 15, 1, 1], 'facecolor', 'black');
rectangle('Position',[7, 15, 1, 1], 'facecolor', 'black');
rectangle('Position',[8, 15, 1, 1], 'facecolor', 'black');
rectangle('Position',[9, 15, 1, 1], 'facecolor', 'black');
rectangle('Position',[13, 15, 1, 1], 'facecolor', 'black');
rectangle('Position',[14, 15, 1, 1], 'facecolor', 'black');
rectangle('Position',[15, 15, 1, 1], 'facecolor', 'black');


hold on;
