clear all;
close all;
dim_x = 35; dim_y = 21;
axis([-1 dim_x -1 dim_y]);
rectangle('Position', [0, 0, 35, 21], 'linewidth',2);
for i=0:20
        rectangle('Position', [0, i, 35, 1]);
end

for i=0:34
        rectangle('Position', [i, 0, 1, 21]);
end

rectangle('Position',[7, 2, 1, 1], 'facecolor', 'black');
rectangle('Position',[8, 2, 1, 1], 'facecolor', 'black');
rectangle('Position',[9, 2, 1, 1], 'facecolor', 'black');
rectangle('Position',[10, 2, 1, 1], 'facecolor', 'black');
rectangle('Position',[11, 2, 1, 1], 'facecolor', 'black');
rectangle('Position',[12, 2, 1, 1], 'facecolor', 'black');
rectangle('Position',[13, 2, 1, 1], 'facecolor', 'black');
rectangle('Position',[14, 2, 1, 1], 'facecolor', 'black');
rectangle('Position',[15, 2, 1, 1], 'facecolor', 'black');
rectangle('Position',[16, 2, 1, 1], 'facecolor', 'black');
rectangle('Position',[18, 2, 1, 1], 'facecolor', 'black');
rectangle('Position',[19, 2, 1, 1], 'facecolor', 'black');
rectangle('Position',[20, 2, 1, 1], 'facecolor', 'black');
rectangle('Position',[21, 2, 1, 1], 'facecolor', 'black');
rectangle('Position',[22, 2, 1, 1], 'facecolor', 'black');
rectangle('Position',[23, 2, 1, 1], 'facecolor', 'black');
rectangle('Position',[24, 2, 1, 1], 'facecolor', 'black');
rectangle('Position',[25, 2, 1, 1], 'facecolor', 'black');
rectangle('Position',[26, 2, 1, 1], 'facecolor', 'black');
rectangle('Position',[27, 2, 1, 1], 'facecolor', 'black');
rectangle('Position',[7, 6, 1, 1], 'facecolor', 'black');
rectangle('Position',[8, 6, 1, 1], 'facecolor', 'black');
rectangle('Position',[9, 6, 1, 1], 'facecolor', 'black');
rectangle('Position',[10, 6, 1, 1], 'facecolor', 'black');
rectangle('Position',[11, 6, 1, 1], 'facecolor', 'black');
rectangle('Position',[12, 6, 1, 1], 'facecolor', 'black');
rectangle('Position',[13, 6, 1, 1], 'facecolor', 'black');
rectangle('Position',[14, 6, 1, 1], 'facecolor', 'black');
rectangle('Position',[15, 6, 1, 1], 'facecolor', 'black');
rectangle('Position',[16, 6, 1, 1], 'facecolor', 'black');
rectangle('Position',[18, 6, 1, 1], 'facecolor', 'black');
rectangle('Position',[19, 6, 1, 1], 'facecolor', 'black');
rectangle('Position',[20, 6, 1, 1], 'facecolor', 'black');
rectangle('Position',[21, 6, 1, 1], 'facecolor', 'black');
rectangle('Position',[22, 6, 1, 1], 'facecolor', 'black');
rectangle('Position',[23, 6, 1, 1], 'facecolor', 'black');
rectangle('Position',[24, 6, 1, 1], 'facecolor', 'black');
rectangle('Position',[25, 6, 1, 1], 'facecolor', 'black');
rectangle('Position',[26, 6, 1, 1], 'facecolor', 'black');
rectangle('Position',[27, 6, 1, 1], 'facecolor', 'black');
rectangle('Position',[7, 10, 1, 1], 'facecolor', 'black');
rectangle('Position',[8, 10, 1, 1], 'facecolor', 'black');
rectangle('Position',[9, 10, 1, 1], 'facecolor', 'black');
rectangle('Position',[10, 10, 1, 1], 'facecolor', 'black');
rectangle('Position',[11, 10, 1, 1], 'facecolor', 'black');
rectangle('Position',[12, 10, 1, 1], 'facecolor', 'black');
rectangle('Position',[13, 10, 1, 1], 'facecolor', 'black');
rectangle('Position',[14, 10, 1, 1], 'facecolor', 'black');
rectangle('Position',[15, 10, 1, 1], 'facecolor', 'black');
rectangle('Position',[16, 10, 1, 1], 'facecolor', 'black');
rectangle('Position',[18, 10, 1, 1], 'facecolor', 'black');
rectangle('Position',[19, 10, 1, 1], 'facecolor', 'black');
rectangle('Position',[20, 10, 1, 1], 'facecolor', 'black');
rectangle('Position',[21, 10, 1, 1], 'facecolor', 'black');
rectangle('Position',[22, 10, 1, 1], 'facecolor', 'black');
rectangle('Position',[23, 10, 1, 1], 'facecolor', 'black');
rectangle('Position',[24, 10, 1, 1], 'facecolor', 'black');
rectangle('Position',[25, 10, 1, 1], 'facecolor', 'black');
rectangle('Position',[26, 10, 1, 1], 'facecolor', 'black');
rectangle('Position',[27, 10, 1, 1], 'facecolor', 'black');
rectangle('Position',[7, 14, 1, 1], 'facecolor', 'black');
rectangle('Position',[8, 14, 1, 1], 'facecolor', 'black');
rectangle('Position',[9, 14, 1, 1], 'facecolor', 'black');
rectangle('Position',[10, 14, 1, 1], 'facecolor', 'black');
rectangle('Position',[11, 14, 1, 1], 'facecolor', 'black');
rectangle('Position',[12, 14, 1, 1], 'facecolor', 'black');
rectangle('Position',[13, 14, 1, 1], 'facecolor', 'black');
rectangle('Position',[14, 14, 1, 1], 'facecolor', 'black');
rectangle('Position',[15, 14, 1, 1], 'facecolor', 'black');
rectangle('Position',[16, 14, 1, 1], 'facecolor', 'black');
rectangle('Position',[18, 14, 1, 1], 'facecolor', 'black');
rectangle('Position',[19, 14, 1, 1], 'facecolor', 'black');
rectangle('Position',[20, 14, 1, 1], 'facecolor', 'black');
rectangle('Position',[21, 14, 1, 1], 'facecolor', 'black');
rectangle('Position',[22, 14, 1, 1], 'facecolor', 'black');
rectangle('Position',[23, 14, 1, 1], 'facecolor', 'black');
rectangle('Position',[24, 14, 1, 1], 'facecolor', 'black');
rectangle('Position',[25, 14, 1, 1], 'facecolor', 'black');
rectangle('Position',[26, 14, 1, 1], 'facecolor', 'black');
rectangle('Position',[27, 14, 1, 1], 'facecolor', 'black');
rectangle('Position',[7, 18, 1, 1], 'facecolor', 'black');
rectangle('Position',[8, 18, 1, 1], 'facecolor', 'black');
rectangle('Position',[9, 18, 1, 1], 'facecolor', 'black');
rectangle('Position',[10, 18, 1, 1], 'facecolor', 'black');
rectangle('Position',[11, 18, 1, 1], 'facecolor', 'black');
rectangle('Position',[12, 18, 1, 1], 'facecolor', 'black');
rectangle('Position',[13, 18, 1, 1], 'facecolor', 'black');
rectangle('Position',[14, 18, 1, 1], 'facecolor', 'black');
rectangle('Position',[15, 18, 1, 1], 'facecolor', 'black');
rectangle('Position',[16, 18, 1, 1], 'facecolor', 'black');
rectangle('Position',[18, 18, 1, 1], 'facecolor', 'black');
rectangle('Position',[19, 18, 1, 1], 'facecolor', 'black');
rectangle('Position',[20, 18, 1, 1], 'facecolor', 'black');
rectangle('Position',[21, 18, 1, 1], 'facecolor', 'black');
rectangle('Position',[22, 18, 1, 1], 'facecolor', 'black');
rectangle('Position',[23, 18, 1, 1], 'facecolor', 'black');
rectangle('Position',[24, 18, 1, 1], 'facecolor', 'black');
rectangle('Position',[25, 18, 1, 1], 'facecolor', 'black');
rectangle('Position',[26, 18, 1, 1], 'facecolor', 'black');
rectangle('Position',[27, 18, 1, 1], 'facecolor', 'black');


hold on;
